baseurl = "/"
title = "sharksforarms"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

[params]
  author = "Emmanuel Thompson"
  info = "Systems development and Rustacean 🦀"
  description = "A dev blog"
  keywords = "blog,developer,personal"
  avatarurl = "avatar.jpg"

  favicon_32 = "favicon.png"
  favicon_16 = "favicon.png"

  since = 2020

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[params.goatCounter]
  code = "sharks"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sharksforarms/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/sharksforarms/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"
